services:
  - type: web
    name: aurora-api
    runtime: docker
    root: aurora-render/backend
    region: ohio
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: aurora-frontend
    runtime: static
    root: aurora-render/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    region: ohio
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: aurora-api
          property: url